"""AUTO-GENERATED Places search areas per state (US Census county names).
Regenerate via scratchpad/gen_counties.py. Each string is one billable
Places call per query phrase."""

from __future__ import annotations

STATE_META: dict[str, dict] = {
    "TX": {"name": "Texas", "slug": "texas", "lat": 31.0, "lng": -99.0},
    "CA": {"name": "California", "slug": "california", "lat": 37.0, "lng": -119.4},
    "KY": {"name": "Kentucky", "slug": "kentucky", "lat": 37.8, "lng": -85.0},
    "GA": {"name": "Georgia", "slug": "georgia", "lat": 32.6, "lng": -83.4},
    "NC": {"name": "North Carolina", "slug": "north-carolina", "lat": 35.6, "lng": -79.4},
}

STATE_COUNTY_AREAS: dict[str, list[str]] = {
    "TX": [
        "Anderson County TX", "Andrews County TX", "Angelina County TX", "Aransas County TX",
        "Archer County TX", "Armstrong County TX", "Atascosa County TX", "Austin County TX",
        "Bailey County TX", "Bandera County TX", "Bastrop County TX", "Baylor County TX",
        "Bee County TX", "Bell County TX", "Bexar County TX", "Blanco County TX",
        "Borden County TX", "Bosque County TX", "Bowie County TX", "Brazoria County TX",
        "Brazos County TX", "Brewster County TX", "Briscoe County TX", "Brooks County TX",
        "Brown County TX", "Burleson County TX", "Burnet County TX", "Caldwell County TX",
        "Calhoun County TX", "Callahan County TX", "Cameron County TX", "Camp County TX",
        "Carson County TX", "Cass County TX", "Castro County TX", "Chambers County TX",
        "Cherokee County TX", "Childress County TX", "Clay County TX", "Cochran County TX",
        "Coke County TX", "Coleman County TX", "Collin County TX", "Collingsworth County TX",
        "Colorado County TX", "Comal County TX", "Comanche County TX", "Concho County TX",
        "Cooke County TX", "Coryell County TX", "Cottle County TX", "Crane County TX",
        "Crockett County TX", "Crosby County TX", "Culberson County TX", "Dallam County TX",
        "Dallas County TX", "Dawson County TX", "DeWitt County TX", "Deaf Smith County TX",
        "Delta County TX", "Denton County TX", "Dickens County TX", "Dimmit County TX",
        "Donley County TX", "Duval County TX", "Eastland County TX", "Ector County TX",
        "Edwards County TX", "El Paso County TX", "Ellis County TX", "Erath County TX",
        "Falls County TX", "Fannin County TX", "Fayette County TX", "Fisher County TX",
        "Floyd County TX", "Foard County TX", "Fort Bend County TX", "Franklin County TX",
        "Freestone County TX", "Frio County TX", "Gaines County TX", "Galveston County TX",
        "Garza County TX", "Gillespie County TX", "Glasscock County TX", "Goliad County TX",
        "Gonzales County TX", "Gray County TX", "Grayson County TX", "Gregg County TX",
        "Grimes County TX", "Guadalupe County TX", "Hale County TX", "Hall County TX",
        "Hamilton County TX", "Hansford County TX", "Hardeman County TX", "Hardin County TX",
        "Harris County TX", "Harrison County TX", "Hartley County TX", "Haskell County TX",
        "Hays County TX", "Hemphill County TX", "Henderson County TX", "Hidalgo County TX",
        "Hill County TX", "Hockley County TX", "Hood County TX", "Hopkins County TX",
        "Houston County TX", "Howard County TX", "Hudspeth County TX", "Hunt County TX",
        "Hutchinson County TX", "Irion County TX", "Jack County TX", "Jackson County TX",
        "Jasper County TX", "Jeff Davis County TX", "Jefferson County TX",
        "Jim Hogg County TX", "Jim Wells County TX", "Johnson County TX", "Jones County TX",
        "Karnes County TX", "Kaufman County TX", "Kendall County TX", "Kenedy County TX",
        "Kent County TX", "Kerr County TX", "Kimble County TX", "King County TX",
        "Kinney County TX", "Kleberg County TX", "Knox County TX", "La Salle County TX",
        "Lamar County TX", "Lamb County TX", "Lampasas County TX", "Lavaca County TX",
        "Lee County TX", "Leon County TX", "Liberty County TX", "Limestone County TX",
        "Lipscomb County TX", "Live Oak County TX", "Llano County TX", "Loving County TX",
        "Lubbock County TX", "Lynn County TX", "Madison County TX", "Marion County TX",
        "Martin County TX", "Mason County TX", "Matagorda County TX", "Maverick County TX",
        "McCulloch County TX", "McLennan County TX", "McMullen County TX", "Medina County TX",
        "Menard County TX", "Midland County TX", "Milam County TX", "Mills County TX",
        "Mitchell County TX", "Montague County TX", "Montgomery County TX", "Moore County TX",
        "Morris County TX", "Motley County TX", "Nacogdoches County TX", "Navarro County TX",
        "Newton County TX", "Nolan County TX", "Nueces County TX", "Ochiltree County TX",
        "Oldham County TX", "Orange County TX", "Palo Pinto County TX", "Panola County TX",
        "Parker County TX", "Parmer County TX", "Pecos County TX", "Polk County TX",
        "Potter County TX", "Presidio County TX", "Rains County TX", "Randall County TX",
        "Reagan County TX", "Real County TX", "Red River County TX", "Reeves County TX",
        "Refugio County TX", "Roberts County TX", "Robertson County TX", "Rockwall County TX",
        "Runnels County TX", "Rusk County TX", "Sabine County TX", "San Augustine County TX",
        "San Jacinto County TX", "San Patricio County TX", "San Saba County TX",
        "Schleicher County TX", "Scurry County TX", "Shackelford County TX",
        "Shelby County TX", "Sherman County TX", "Smith County TX", "Somervell County TX",
        "Starr County TX", "Stephens County TX", "Sterling County TX", "Stonewall County TX",
        "Sutton County TX", "Swisher County TX", "Tarrant County TX", "Taylor County TX",
        "Terrell County TX", "Terry County TX", "Throckmorton County TX", "Titus County TX",
        "Tom Green County TX", "Travis County TX", "Trinity County TX", "Tyler County TX",
        "Upshur County TX", "Upton County TX", "Uvalde County TX", "Val Verde County TX",
        "Van Zandt County TX", "Victoria County TX", "Walker County TX", "Waller County TX",
        "Ward County TX", "Washington County TX", "Webb County TX", "Wharton County TX",
        "Wheeler County TX", "Wichita County TX", "Wilbarger County TX", "Willacy County TX",
        "Williamson County TX", "Wilson County TX", "Winkler County TX", "Wise County TX",
        "Wood County TX", "Yoakum County TX", "Young County TX", "Zapata County TX",
        "Zavala County TX",
    ],
    "CA": [
        "Alameda County CA", "Alpine County CA", "Amador County CA", "Butte County CA",
        "Calaveras County CA", "Colusa County CA", "Contra Costa County CA",
        "Del Norte County CA", "El Dorado County CA", "Fresno County CA", "Glenn County CA",
        "Humboldt County CA", "Imperial County CA", "Inyo County CA", "Kern County CA",
        "Kings County CA", "Lake County CA", "Lassen County CA", "Los Angeles County CA",
        "Madera County CA", "Marin County CA", "Mariposa County CA", "Mendocino County CA",
        "Merced County CA", "Modoc County CA", "Mono County CA", "Monterey County CA",
        "Napa County CA", "Nevada County CA", "Orange County CA", "Placer County CA",
        "Plumas County CA", "Riverside County CA", "Sacramento County CA",
        "San Benito County CA", "San Bernardino County CA", "San Diego County CA",
        "San Francisco County CA", "San Joaquin County CA", "San Luis Obispo County CA",
        "San Mateo County CA", "Santa Barbara County CA", "Santa Clara County CA",
        "Santa Cruz County CA", "Shasta County CA", "Sierra County CA", "Siskiyou County CA",
        "Solano County CA", "Sonoma County CA", "Stanislaus County CA", "Sutter County CA",
        "Tehama County CA", "Trinity County CA", "Tulare County CA", "Tuolumne County CA",
        "Ventura County CA", "Yolo County CA", "Yuba County CA",
    ],
    "KY": [
        "Adair County KY", "Allen County KY", "Anderson County KY", "Ballard County KY",
        "Barren County KY", "Bath County KY", "Bell County KY", "Boone County KY",
        "Bourbon County KY", "Boyd County KY", "Boyle County KY", "Bracken County KY",
        "Breathitt County KY", "Breckinridge County KY", "Bullitt County KY",
        "Butler County KY", "Caldwell County KY", "Calloway County KY", "Campbell County KY",
        "Carlisle County KY", "Carroll County KY", "Carter County KY", "Casey County KY",
        "Christian County KY", "Clark County KY", "Clay County KY", "Clinton County KY",
        "Crittenden County KY", "Cumberland County KY", "Daviess County KY",
        "Edmonson County KY", "Elliott County KY", "Estill County KY", "Fayette County KY",
        "Fleming County KY", "Floyd County KY", "Franklin County KY", "Fulton County KY",
        "Gallatin County KY", "Garrard County KY", "Grant County KY", "Graves County KY",
        "Grayson County KY", "Green County KY", "Greenup County KY", "Hancock County KY",
        "Hardin County KY", "Harlan County KY", "Harrison County KY", "Hart County KY",
        "Henderson County KY", "Henry County KY", "Hickman County KY", "Hopkins County KY",
        "Jackson County KY", "Jefferson County KY", "Jessamine County KY", "Johnson County KY",
        "Kenton County KY", "Knott County KY", "Knox County KY", "Larue County KY",
        "Laurel County KY", "Lawrence County KY", "Lee County KY", "Leslie County KY",
        "Letcher County KY", "Lewis County KY", "Lincoln County KY", "Livingston County KY",
        "Logan County KY", "Lyon County KY", "Madison County KY", "Magoffin County KY",
        "Marion County KY", "Marshall County KY", "Martin County KY", "Mason County KY",
        "McCracken County KY", "McCreary County KY", "McLean County KY", "Meade County KY",
        "Menifee County KY", "Mercer County KY", "Metcalfe County KY", "Monroe County KY",
        "Montgomery County KY", "Morgan County KY", "Muhlenberg County KY", "Nelson County KY",
        "Nicholas County KY", "Ohio County KY", "Oldham County KY", "Owen County KY",
        "Owsley County KY", "Pendleton County KY", "Perry County KY", "Pike County KY",
        "Powell County KY", "Pulaski County KY", "Robertson County KY", "Rockcastle County KY",
        "Rowan County KY", "Russell County KY", "Scott County KY", "Shelby County KY",
        "Simpson County KY", "Spencer County KY", "Taylor County KY", "Todd County KY",
        "Trigg County KY", "Trimble County KY", "Union County KY", "Warren County KY",
        "Washington County KY", "Wayne County KY", "Webster County KY", "Whitley County KY",
        "Wolfe County KY", "Woodford County KY",
    ],
    "GA": [
        "Appling County GA", "Atkinson County GA", "Bacon County GA", "Baker County GA",
        "Baldwin County GA", "Banks County GA", "Barrow County GA", "Bartow County GA",
        "Ben Hill County GA", "Berrien County GA", "Bibb County GA", "Bleckley County GA",
        "Brantley County GA", "Brooks County GA", "Bryan County GA", "Bulloch County GA",
        "Burke County GA", "Butts County GA", "Calhoun County GA", "Camden County GA",
        "Candler County GA", "Carroll County GA", "Catoosa County GA", "Charlton County GA",
        "Chatham County GA", "Chattahoochee County GA", "Chattooga County GA",
        "Cherokee County GA", "Clarke County GA", "Clay County GA", "Clayton County GA",
        "Clinch County GA", "Cobb County GA", "Coffee County GA", "Colquitt County GA",
        "Columbia County GA", "Cook County GA", "Coweta County GA", "Crawford County GA",
        "Crisp County GA", "Dade County GA", "Dawson County GA", "DeKalb County GA",
        "Decatur County GA", "Dodge County GA", "Dooly County GA", "Dougherty County GA",
        "Douglas County GA", "Early County GA", "Echols County GA", "Effingham County GA",
        "Elbert County GA", "Emanuel County GA", "Evans County GA", "Fannin County GA",
        "Fayette County GA", "Floyd County GA", "Forsyth County GA", "Franklin County GA",
        "Fulton County GA", "Gilmer County GA", "Glascock County GA", "Glynn County GA",
        "Gordon County GA", "Grady County GA", "Greene County GA", "Gwinnett County GA",
        "Habersham County GA", "Hall County GA", "Hancock County GA", "Haralson County GA",
        "Harris County GA", "Hart County GA", "Heard County GA", "Henry County GA",
        "Houston County GA", "Irwin County GA", "Jackson County GA", "Jasper County GA",
        "Jeff Davis County GA", "Jefferson County GA", "Jenkins County GA",
        "Johnson County GA", "Jones County GA", "Lamar County GA", "Lanier County GA",
        "Laurens County GA", "Lee County GA", "Liberty County GA", "Lincoln County GA",
        "Long County GA", "Lowndes County GA", "Lumpkin County GA", "Macon County GA",
        "Madison County GA", "Marion County GA", "McDuffie County GA", "McIntosh County GA",
        "Meriwether County GA", "Miller County GA", "Mitchell County GA", "Monroe County GA",
        "Montgomery County GA", "Morgan County GA", "Murray County GA", "Muscogee County GA",
        "Newton County GA", "Oconee County GA", "Oglethorpe County GA", "Paulding County GA",
        "Peach County GA", "Pickens County GA", "Pierce County GA", "Pike County GA",
        "Polk County GA", "Pulaski County GA", "Putnam County GA", "Quitman County GA",
        "Rabun County GA", "Randolph County GA", "Richmond County GA", "Rockdale County GA",
        "Schley County GA", "Screven County GA", "Seminole County GA", "Spalding County GA",
        "Stephens County GA", "Stewart County GA", "Sumter County GA", "Talbot County GA",
        "Taliaferro County GA", "Tattnall County GA", "Taylor County GA", "Telfair County GA",
        "Terrell County GA", "Thomas County GA", "Tift County GA", "Toombs County GA",
        "Towns County GA", "Treutlen County GA", "Troup County GA", "Turner County GA",
        "Twiggs County GA", "Union County GA", "Upson County GA", "Walker County GA",
        "Walton County GA", "Ware County GA", "Warren County GA", "Washington County GA",
        "Wayne County GA", "Webster County GA", "Wheeler County GA", "White County GA",
        "Whitfield County GA", "Wilcox County GA", "Wilkes County GA", "Wilkinson County GA",
        "Worth County GA",
    ],
    "NC": [
        "Alamance County NC", "Alexander County NC", "Alleghany County NC", "Anson County NC",
        "Ashe County NC", "Avery County NC", "Beaufort County NC", "Bertie County NC",
        "Bladen County NC", "Brunswick County NC", "Buncombe County NC", "Burke County NC",
        "Cabarrus County NC", "Caldwell County NC", "Camden County NC", "Carteret County NC",
        "Caswell County NC", "Catawba County NC", "Chatham County NC", "Cherokee County NC",
        "Chowan County NC", "Clay County NC", "Cleveland County NC", "Columbus County NC",
        "Craven County NC", "Cumberland County NC", "Currituck County NC", "Dare County NC",
        "Davidson County NC", "Davie County NC", "Duplin County NC", "Durham County NC",
        "Edgecombe County NC", "Forsyth County NC", "Franklin County NC", "Gaston County NC",
        "Gates County NC", "Graham County NC", "Granville County NC", "Greene County NC",
        "Guilford County NC", "Halifax County NC", "Harnett County NC", "Haywood County NC",
        "Henderson County NC", "Hertford County NC", "Hoke County NC", "Hyde County NC",
        "Iredell County NC", "Jackson County NC", "Johnston County NC", "Jones County NC",
        "Lee County NC", "Lenoir County NC", "Lincoln County NC", "Macon County NC",
        "Madison County NC", "Martin County NC", "McDowell County NC", "Mecklenburg County NC",
        "Mitchell County NC", "Montgomery County NC", "Moore County NC", "Nash County NC",
        "New Hanover County NC", "Northampton County NC", "Onslow County NC",
        "Orange County NC", "Pamlico County NC", "Pasquotank County NC", "Pender County NC",
        "Perquimans County NC", "Person County NC", "Pitt County NC", "Polk County NC",
        "Randolph County NC", "Richmond County NC", "Robeson County NC",
        "Rockingham County NC", "Rowan County NC", "Rutherford County NC", "Sampson County NC",
        "Scotland County NC", "Stanly County NC", "Stokes County NC", "Surry County NC",
        "Swain County NC", "Transylvania County NC", "Tyrrell County NC", "Union County NC",
        "Vance County NC", "Wake County NC", "Warren County NC", "Washington County NC",
        "Watauga County NC", "Wayne County NC", "Wilkes County NC", "Wilson County NC",
        "Yadkin County NC", "Yancey County NC",
    ],
}
